# ref. https://gist.github.com/terrywang/3950393
# /home/terrywang/.tmux.conf
# Based on tmux book written by Brian P. Hogan
# c-a o to switch to another panel
# c-a d to close shell
# c-a ! to close panel
# c-a w to list windows
# c-a " split pane horizontally
# c-a % split pane vertically

set-option -g default-shell /bin/zsh

# Plugin list
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'jimeh/tmux-themepack'
set -g @themepack 'powerline/block/cyan'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @resurrect-strategy-vim 'session'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-open'

# Setting the prefix from C-b to C-a
set -g prefix C-a

# Free the original Ctrl-b prefix keybinding
unbind C-b

# Ensure that we can send Ctrl-a to other apps
bind C-a send-prefix

# Set the base index for windows to 1 instead of 0
set -g base-index 1

# Set the base index for panes to 1 instead of 0
setw -g pane-base-index 1

# Switch to last window
unbind l
bind a last-window

# Reload the file with Prefix r
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# Splitting panes replace % and "
bind | split-window -h
bind - split-window -v

# moving between panes
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Quick pane selection
bind -r C-h select-window -t :-
bind -r C-l select-window -t :+

# Pane resizing
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# Set the default terminal mode to 256color mode
set -g default-terminal xterm-256color
set -g terminal-overrides 'xterm:colors=256'

# Enable activity alerts
setw -g monitor-activity on
set -g visual-activity on

# Update the status bar every five seconds
set -g status-interval 5

# Center the window list
set -g status-justify centre

# Enable vi keys
setw -g mode-keys vi

# Initialize TPM
run -b '~/.tmux/plugins/tpm/tpm'
